FOR /D %%I IN (*.*) DO RMDIR /S /Q "%%I\Recent"
FOR /D %%I IN (*.*) DO RMDIR /S /Q "%%I\Application Data\Talkback\MozillaOrg"
FOR /D %%I IN (*.*) DO RMDIR /S /Q "%%I\Application Data\Mozilla\Firefox"
FOR /D %%I IN (*.*) DO RMDIR /S /Q "%%I\Application Data\ICQLite"
FOR /D %%I IN (*.*) DO RMDIR /S /Q "%%I\Application Data\Microsoft\Office\Recent"
FOR /D %%I IN (*.*) DO RMDIR /S /Q "%%I\Application Data\Skype"
FOR /D %%I IN (*.*) DO RMDIR /S /Q "%%I\Application Data\Macromedia\Flash Player"
FOR /D %%I IN (*.*) DO RMDIR /S /Q "%%I\Application Data\Sun\Java"
FOR /D %%I IN (*.*) DO RMDIR /S /Q "%%I\Application Data\Opera"
